kind: pipeline
name: arm64

platform:
  arch:
  - arm64
  - arm

steps:
- name: test
  image: rust:latest
  commands:
  - apt-get update -qq --yes && apt-get install -qq --yes clang
  - git submodule update --init --recursive
  - cargo build --verbose --features rust-crypto-aes
  - cargo test --verbose --features rust-crypto-aes
  - cargo test --verbose --all-features
