name: Deploy Docs

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: evercrypt-rs

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@master
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build docs
        run: |
          cargo doc --all-features --no-deps
          touch target/doc/.nojekyll
          cat > target/doc/index.html <<EOF
          <!doctype html>
          <html><head>
            <meta http-equiv="refresh" content="0; URL='evercrypt/index.html'" />
          </head></html>
          EOF
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc
